/* TrainSheet AI Version: 0.7.0 */
const cameraInput=document.getElementById("cameraInput"),galleryInput=document.getElementById("galleryInput"),previewCard=document.getElementById("previewCard"),previewImage=document.getElementById("previewImage"),overlayCanvas=document.getElementById("overlayCanvas"),startBtn=document.getElementById("startBtn"),clearBtn=document.getElementById("clearBtn"),statusText=document.getElementById("statusText"),workflowState=document.getElementById("workflowState"),lineCount=document.getElementById("lineCount"),gridCount=document.getElementById("gridCount"),targetPanel=document.getElementById("targetPanel"),targetCanvas=document.getElementById("targetCanvas"),rowPanel=document.getElementById("rowPanel"),rowCanvas=document.getElementById("rowCanvas"),targetScore=document.getElementById("targetScore");
let currentImage=null,currentImageUrl=null,analysis=null;
function handleImage(file){if(!file)return;if(currentImageUrl)URL.revokeObjectURL(currentImageUrl);currentImageUrl=URL.createObjectURL(file);const img=new Image();img.onload=()=>{currentImage=img;previewImage.src=currentImageUrl;previewCard.classList.remove("hidden");startBtn.disabled=false;reset();statusText.textContent="照片已载入。点击开始，程序会真正检测表格横线和竖线。"};img.src=currentImageUrl}
cameraInput.addEventListener("change",()=>handleImage(cameraInput.files[0]));galleryInput.addEventListener("change",()=>handleImage(galleryInput.files[0]));
clearBtn.addEventListener("click",()=>{if(currentImageUrl)URL.revokeObjectURL(currentImageUrl);currentImageUrl=null;currentImage=null;previewImage.src="";previewCard.classList.add("hidden");startBtn.disabled=true;reset();statusText.textContent="请先拍照或从相册选择一张完整图片。"});
startBtn.addEventListener("click",async()=>{if(!currentImage)return;startBtn.disabled=true;reset(false);await step("photo","正在读取照片……");await step("gray","正在转灰度并增强线条……");analysis=analyzeGrid(currentImage);await step("lines","正在检测横线和竖线……");drawOverlay(analysis);lineCount.textContent=analysis.hLines.length+analysis.vLines.length;gridCount.textContent=analysis.target?1:0;await step("target","正在寻找右侧网格……");drawTarget(analysis);await step("crop","正在裁切目标区域……");statusText.textContent=analysis.target?"已找到一个目标区域候选。请看橙色框是否包含右侧31～61。":"未找到可靠目标区域，下一版会继续加强算法。";startBtn.disabled=false});
function analyzeGrid(img){const maxW=900,scale=Math.min(1,maxW/img.naturalWidth),w=Math.round(img.naturalWidth*scale),h=Math.round(img.naturalHeight*scale);const c=document.createElement("canvas"),ctx=c.getContext("2d");c.width=w;c.height=h;ctx.drawImage(img,0,0,w,h);const data=ctx.getImageData(0,0,w,h).data;const dark=new Uint8Array(w*h);for(let y=0;y<h;y++){for(let x=0;x<w;x++){const i=(y*w+x)*4,r=data[i],g=data[i+1],b=data[i+2];const gray=.299*r+.587*g+.114*b;dark[y*w+x]=gray<115?1:0}}
const hScore=new Array(h).fill(0),vScore=new Array(w).fill(0);
for(let y=0;y<h;y++){let run=0,best=0;for(let x=0;x<w;x++){if(dark[y*w+x]){run++; if(run>best)best=run}else run=0}hScore[y]=best}
for(let x=0;x<w;x++){let run=0,best=0;for(let y=0;y<h;y++){if(dark[y*w+x]){run++; if(run>best)best=run}else run=0}vScore[x]=best}
const hLines=clusterLines(hScore,Math.max(80,w*.18),4).map(y=>y/scale);
const vLines=clusterLines(vScore,Math.max(60,h*.10),4).map(x=>x/scale);
const target=findTarget(hLines,vLines,img.naturalWidth,img.naturalHeight);
return{scale,hLines,vLines,target}}
function clusterLines(score,threshold,gap){const arr=[];let start=-1,sum=0,count=0;for(let i=0;i<score.length;i++){if(score[i]>=threshold){if(start<0){start=i;sum=0;count=0}sum+=i;count++}else if(start>=0){if(count>=1)arr.push(Math.round(sum/count));start=-1}}if(start>=0&&count>=1)arr.push(Math.round(sum/count));return mergeClose(arr,gap)}
function mergeClose(a,gap){if(!a.length)return[];const out=[a[0]];for(let i=1;i<a.length;i++){if(a[i]-out[out.length-1]<gap)out[out.length-1]=Math.round((out[out.length-1]+a[i])/2);else out.push(a[i])}return out}
function findTarget(hLines,vLines,W,H){if(hLines.length<8||vLines.length<4)return null;const xs=vLines.filter(x=>x>W*.45).sort((a,b)=>a-b);const ys=hLines.filter(y=>y>H*.05&&y<H*.95).sort((a,b)=>a-b);if(xs.length<3||ys.length<10)return null;let x1=xs[Math.max(0,xs.length-4)],x2=xs[xs.length-1];let y1=ys[0],y2=ys[ys.length-1];if(x2-x1<W*.12){x1=W*.62;x2=W*.96}return{x:x1,y:y1,w:x2-x1,h:y2-y1}}
function drawOverlay(res){const box=previewImage.getBoundingClientRect();overlayCanvas.width=box.width;overlayCanvas.height=box.height;const ctx=overlayCanvas.getContext("2d");ctx.clearRect(0,0,box.width,box.height);const sx=box.width/currentImage.naturalWidth,sy=box.height/currentImage.naturalHeight;ctx.lineWidth=1.5;ctx.strokeStyle="rgba(37,99,235,.65)";res.hLines.forEach(y=>{ctx.beginPath();ctx.moveTo(0,y*sy);ctx.lineTo(box.width,y*sy);ctx.stroke()});ctx.strokeStyle="rgba(22,163,74,.75)";res.vLines.forEach(x=>{ctx.beginPath();ctx.moveTo(x*sx,0);ctx.lineTo(x*sx,box.height);ctx.stroke()});if(res.target){ctx.strokeStyle="#f59e0b";ctx.lineWidth=4;ctx.strokeRect(res.target.x*sx,res.target.y*sy,res.target.w*sx,res.target.h*sy)}}
function drawTarget(res){if(!res.target){targetPanel.classList.add("hidden");rowPanel.classList.add("hidden");targetScore.textContent="未找到";return}const r=res.target;targetPanel.classList.remove("hidden");rowPanel.classList.remove("hidden");drawCrop(targetCanvas,r,false);drawCrop(rowCanvas,r,true);targetScore.textContent="候选区域"}
function drawCrop(canvas,r,rows){const ratio=r.h/r.w;canvas.width=520;canvas.height=Math.max(260,Math.round(520*ratio));const ctx=canvas.getContext("2d");ctx.drawImage(currentImage,r.x,r.y,r.w,r.h,0,0,canvas.width,canvas.height);ctx.strokeStyle="#f59e0b";ctx.lineWidth=6;ctx.strokeRect(3,3,canvas.width-6,canvas.height-6);if(rows){ctx.strokeStyle="rgba(37,99,235,.9)";ctx.lineWidth=1.3;for(let i=0;i<=31;i++){const y=i*canvas.height/31;ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(canvas.width,y);ctx.stroke()}}}
function reset(clear=true){clearSteps();workflowState.textContent="等待处理";lineCount.textContent="0";gridCount.textContent="0";targetPanel.classList.add("hidden");rowPanel.classList.add("hidden");const ctx=overlayCanvas.getContext("2d");ctx.clearRect(0,0,overlayCanvas.width,overlayCanvas.height);if(clear)analysis=null}
function clearSteps(){document.querySelectorAll(".step").forEach(s=>s.classList.remove("active","done"))}
function done(n){const s=document.querySelector(`[data-step="${n}"]`);if(s){s.classList.remove("active");s.classList.add("done")}}
async function step(n,t){workflowState.textContent=t.replace("……","");statusText.textContent=t;document.querySelector(`[data-step="${n}"]`)?.classList.add("active");await new Promise(r=>setTimeout(r,300));done(n)}
if("serviceWorker"in navigator){navigator.serviceWorker.register("sw.js").catch(()=>{})}