/* TrainSheet AI Version: 0.6.0 */
const cameraInput=document.getElementById("cameraInput"),galleryInput=document.getElementById("galleryInput"),previewCard=document.getElementById("previewCard"),previewImage=document.getElementById("previewImage"),overlayCanvas=document.getElementById("overlayCanvas"),startBtn=document.getElementById("startBtn"),clearBtn=document.getElementById("clearBtn"),statusText=document.getElementById("statusText"),workflowState=document.getElementById("workflowState"),resultBody=document.getElementById("resultBody"),learnCount=document.getElementById("learnCount"),needConfirmCount=document.getElementById("needConfirmCount"),confirmPanel=document.getElementById("confirmPanel"),confirmIndex=document.getElementById("confirmIndex"),confirmTitle=document.getElementById("confirmTitle"),confirmReason=document.getElementById("confirmReason"),trainCandidates=document.getElementById("trainCandidates"),trackCandidates=document.getElementById("trackCandidates"),manualTrain=document.getElementById("manualTrain"),manualTrack=document.getElementById("manualTrack"),confirmBtn=document.getElementById("confirmBtn"),prevBtn=document.getElementById("prevBtn"),cellCanvas=document.getElementById("cellCanvas"),memoryList=document.getElementById("memoryList"),clearMemoryBtn=document.getElementById("clearMemoryBtn"),demoBtn=document.getElementById("demoBtn");
let currentImageUrl=null,currentImage=null,confirmQueue=[],confirmPointer=0,selectedTrain="",selectedTrack="",results=[];
const STORAGE_KEY="trainsheet_learning_memory_v2";
function loadMemory(){try{return JSON.parse(localStorage.getItem(STORAGE_KEY)||"[]")}catch{return[]}}
function saveMemory(m){localStorage.setItem(STORAGE_KEY,JSON.stringify(m));renderMemory()}
function addMemory(type,raw,correct){const memory=loadMemory();const key=type+"|"+raw+"|"+correct;const item=memory.find(x=>x.key===key);if(item){item.times+=1;item.updatedAt=Date.now()}else{memory.unshift({key,type,raw,correct,times:1,updatedAt:Date.now()})}saveMemory(memory.slice(0,120))}
function renderMemory(){const m=loadMemory();learnCount.textContent=m.reduce((s,x)=>s+x.times,0);if(!m.length){memoryList.innerHTML='<div class="memory-item"><span>暂无学习记录</span><span>确认后自动保存</span></div>';return}memoryList.innerHTML=m.slice(0,8).map(x=>`<div class="memory-item"><strong>${x.raw} → ${x.correct}</strong><span>${x.times} 次</span></div>`).join("")}
function handleImage(file){if(!file)return;if(currentImageUrl)URL.revokeObjectURL(currentImageUrl);currentImageUrl=URL.createObjectURL(file);const img=new Image();img.onload=()=>{currentImage=img;previewImage.src=currentImageUrl;previewCard.classList.remove("hidden");startBtn.disabled=false;resetWorkflow();clearResults();confirmPanel.classList.add("hidden");statusText.textContent="照片已载入。点击“开始处理”，查看放大确认流程。"};img.src=currentImageUrl}
cameraInput.addEventListener("change",()=>handleImage(cameraInput.files[0]));galleryInput.addEventListener("change",()=>handleImage(galleryInput.files[0]));
clearBtn.addEventListener("click",()=>{if(currentImageUrl)URL.revokeObjectURL(currentImageUrl);currentImageUrl=null;currentImage=null;previewImage.src="";previewCard.classList.add("hidden");startBtn.disabled=true;resetWorkflow();clearResults();confirmPanel.classList.add("hidden");clearOverlay();statusText.textContent="请先拍照或从相册选择一张完整图片。"});
startBtn.addEventListener("click",async()=>{startBtn.disabled=true;resetWorkflow();clearResults();await runStep("photo","正在读取照片……");await runStep("target","正在定位目标区……");await runStep("rows","正在生成待确认格……");prepareConfirmDemo();await runStep("confirm","进入放大确认……");startBtn.disabled=false});
demoBtn.addEventListener("click",()=>{prepareConfirmDemo();renderResults()});
clearMemoryBtn.addEventListener("click",()=>{if(confirm("确定清空本地学习记忆吗？"))saveMemory([])});
function prepareConfirmDemo(){confirmQueue=[{row:31,reason:"车号笔迹接近，需要根据放大图确认。",train:["020","028","029"],track:["04东","04西","14西"],rawTrain:"02?",rawTrack:"04?",box:{x:.70,y:.18,w:.22,h:.055}},{row:44,reason:"股道 A/C 不够清楚，需要确认。",train:["077","072","078"],track:["17东","17西","11东"],rawTrain:"07?",rawTrack:"17?",box:{x:.70,y:.46,w:.22,h:.055}},{row:56,reason:"疑似有修改痕迹，程序不应自动判断。",train:["035","025","038"],track:["05西","15西","05东"],rawTrain:"03?",rawTrack:"05?",box:{x:.70,y:.69,w:.22,h:.055}}];confirmPointer=0;results=[];needConfirmCount.textContent=confirmQueue.length;confirmPanel.classList.remove("hidden");showConfirmItem();confirmPanel.scrollIntoView({behavior:"smooth",block:"start"})}
function showConfirmItem(){if(confirmPointer>=confirmQueue.length){confirmPanel.classList.add("hidden");needConfirmCount.textContent="0";statusText.textContent="人工确认完成，学习记忆已更新。";renderResults();return}const item=confirmQueue[confirmPointer];selectedTrain=item.train[0];selectedTrack=item.track[0];confirmIndex.textContent=`${confirmPointer+1} / ${confirmQueue.length}`;confirmTitle.textContent=`请确认这一格`;confirmReason.textContent=`位置：右侧目标区第 ${item.row} 项。${item.reason}`;manualTrain.value="";manualTrack.value="";renderCandidateButtons(trainCandidates,item.train,"train");renderCandidateButtons(trackCandidates,item.track,"track");drawCurrentBox(item);drawCellCrop(item)}
function renderCandidateButtons(container,arr,type){container.innerHTML=arr.map((x,i)=>`<button class="candidate-btn ${i===0?'selected':''}" data-type="${type}" data-value="${x}">${x}</button>`).join("");container.querySelectorAll("button").forEach(btn=>btn.addEventListener("click",()=>{container.querySelectorAll("button").forEach(b=>b.classList.remove("selected"));btn.classList.add("selected");if(type==="train")selectedTrain=btn.dataset.value;else selectedTrack=btn.dataset.value}))}
function drawCurrentBox(item){if(!currentImage)return;const box=previewImage.getBoundingClientRect();overlayCanvas.width=box.width;overlayCanvas.height=box.height;const ctx=overlayCanvas.getContext("2d");ctx.clearRect(0,0,overlayCanvas.width,overlayCanvas.height);const b=item.box;ctx.strokeStyle="#dc2626";ctx.lineWidth=4;ctx.setLineDash([8,5]);ctx.strokeRect(b.x*box.width,b.y*box.height,b.w*box.width,b.h*box.height)}
function clearOverlay(){const ctx=overlayCanvas.getContext("2d");ctx.clearRect(0,0,overlayCanvas.width,overlayCanvas.height)}
function drawCellCrop(item){const ctx=cellCanvas.getContext("2d");cellCanvas.width=900;cellCanvas.height=260;ctx.fillStyle="#fff";ctx.fillRect(0,0,cellCanvas.width,cellCanvas.height);if(!currentImage){ctx.fillStyle="#111827";ctx.font="bold 58px sans-serif";ctx.fillText("示例放大格",250,130);return}const b=item.box;const sx=b.x*currentImage.naturalWidth,sy=b.y*currentImage.naturalHeight,sw=b.w*currentImage.naturalWidth,sh=b.h*currentImage.naturalHeight;const padY=sh*1.6;const cropY=Math.max(0,sy-padY);const cropH=Math.min(currentImage.naturalHeight-cropY,sh+padY*2);ctx.drawImage(currentImage,sx,cropY,sw,cropH,0,0,cellCanvas.width,cellCanvas.height);ctx.strokeStyle="#2563eb";ctx.lineWidth=8;ctx.strokeRect(8,cellCanvas.height*.34,cellCanvas.width-16,cellCanvas.height*.32)}
confirmBtn.addEventListener("click",()=>{const item=confirmQueue[confirmPointer];const finalTrain=(manualTrain.value||selectedTrain).trim();const finalTrack=(manualTrack.value||selectedTrack).trim();if(!finalTrain||!finalTrack){alert("请确认车号和股道");return}results.push({row:item.row,time:"固定时刻",track:finalTrack,train:finalTrain,status:"已确认"});addMemory("train",item.rawTrain,finalTrain);addMemory("track",item.rawTrack,finalTrack);confirmPointer++;showConfirmItem();renderResults()});
prevBtn.addEventListener("click",()=>{if(confirmPointer>0){confirmPointer--;showConfirmItem()}});
function renderResults(){if(!results.length){resultBody.innerHTML='<tr class="empty-row"><td colspan="5">暂无结果</td></tr>';return}resultBody.innerHTML=results.map(r=>`<tr><td>${r.row}</td><td>${r.time}</td><td>${r.track}</td><td>${r.train}</td><td class="ok">${r.status}</td></tr>`).join("")}
function clearResults(){results=[];resultBody.innerHTML='<tr class="empty-row"><td colspan="5">暂无结果</td></tr>';needConfirmCount.textContent="0"}
function resetWorkflow(){clearSteps();workflowState.textContent="等待处理"}
function clearSteps(){document.querySelectorAll(".step").forEach(s=>s.classList.remove("active","done"))}
function markDone(n){const s=document.querySelector(`[data-step="${n}"]`);if(!s)return;s.classList.remove("active");s.classList.add("done")}
async function runStep(n,t){workflowState.textContent=t.replace("……","");statusText.textContent=t;document.querySelector(`[data-step="${n}"]`)?.classList.add("active");await new Promise(r=>setTimeout(r,430));markDone(n)}
renderMemory();
if("serviceWorker"in navigator){navigator.serviceWorker.register("sw.js").catch(()=>{})}
